/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "hydroponic_data.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(hydroponic_Hydroponic, hydroponic_Hydroponic, AUTO)


PB_BIND(hydroponic_DataPackage, hydroponic_DataPackage, AUTO)


PB_BIND(hydroponic_HeartBeat, hydroponic_HeartBeat, AUTO)


PB_BIND(hydroponic_MessageOk, hydroponic_MessageOk, AUTO)


PB_BIND(hydroponic_MessageError, hydroponic_MessageError, AUTO)


PB_BIND(hydroponic_MessageTimeout, hydroponic_MessageTimeout, AUTO)


PB_BIND(hydroponic_Command, hydroponic_Command, AUTO)





