/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_HYDROPONIC_HYDROPONIC_DATA_PB_H_INCLUDED
#define PB_HYDROPONIC_HYDROPONIC_DATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _hydroponic_MessageType {
    hydroponic_MessageType_MSG_HEART_BEAT = 0,
    hydroponic_MessageType_MSG_OK = 1,
    hydroponic_MessageType_MSG_ERROR = 2,
    hydroponic_MessageType_MSG_DATA = 3,
    hydroponic_MessageType_MSG_TIMEOUT = 4
} hydroponic_MessageType;

/* Struct definitions */
typedef struct _hydroponic_DataPackage {
    uint32_t deviceID;
    pb_callback_t sector;
    float eConductivity;
    float ph;
    float moisture;
    float temperature;
    uint32_t waterLevel;
    bool valveState;
    bool pumpState;
    bool ledStatus;
} hydroponic_DataPackage;

typedef struct _hydroponic_HeartBeat {
    uint32_t elapsedTime;
} hydroponic_HeartBeat;

typedef struct _hydroponic_MessageOk {
    pb_callback_t responseMessage;
} hydroponic_MessageOk;

typedef struct _hydroponic_MessageError {
    pb_callback_t errorType;
} hydroponic_MessageError;

typedef struct _hydroponic_MessageTimeout {
    pb_callback_t timeoutMessage;
} hydroponic_MessageTimeout;

typedef struct _hydroponic_Hydroponic {
    hydroponic_MessageType messageType;
    pb_callback_t cb_msg;
    pb_size_t which_msg;
    union {
        hydroponic_DataPackage dataPackage;
        hydroponic_HeartBeat heartBeat;
        hydroponic_MessageOk messageOk;
        hydroponic_MessageError messageError;
        hydroponic_MessageTimeout messageTimeout;
    } msg;
} hydroponic_Hydroponic;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _hydroponic_MessageType_MIN hydroponic_MessageType_MSG_HEART_BEAT
#define _hydroponic_MessageType_MAX hydroponic_MessageType_MSG_TIMEOUT
#define _hydroponic_MessageType_ARRAYSIZE ((hydroponic_MessageType)(hydroponic_MessageType_MSG_TIMEOUT+1))

#define hydroponic_Hydroponic_messageType_ENUMTYPE hydroponic_MessageType







/* Initializer values for message structs */
#define hydroponic_Hydroponic_init_default       {_hydroponic_MessageType_MIN, {{NULL}, NULL}, 0, {hydroponic_DataPackage_init_default}}
#define hydroponic_DataPackage_init_default      {0, {{NULL}, NULL}, 0, 0, 0, 0, 0, 0, 0, 0}
#define hydroponic_HeartBeat_init_default        {0}
#define hydroponic_MessageOk_init_default        {{{NULL}, NULL}}
#define hydroponic_MessageError_init_default     {{{NULL}, NULL}}
#define hydroponic_MessageTimeout_init_default   {{{NULL}, NULL}}
#define hydroponic_Hydroponic_init_zero          {_hydroponic_MessageType_MIN, {{NULL}, NULL}, 0, {hydroponic_DataPackage_init_zero}}
#define hydroponic_DataPackage_init_zero         {0, {{NULL}, NULL}, 0, 0, 0, 0, 0, 0, 0, 0}
#define hydroponic_HeartBeat_init_zero           {0}
#define hydroponic_MessageOk_init_zero           {{{NULL}, NULL}}
#define hydroponic_MessageError_init_zero        {{{NULL}, NULL}}
#define hydroponic_MessageTimeout_init_zero      {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define hydroponic_DataPackage_deviceID_tag      2
#define hydroponic_DataPackage_sector_tag        3
#define hydroponic_DataPackage_eConductivity_tag 4
#define hydroponic_DataPackage_ph_tag            5
#define hydroponic_DataPackage_moisture_tag      6
#define hydroponic_DataPackage_temperature_tag   7
#define hydroponic_DataPackage_waterLevel_tag    8
#define hydroponic_DataPackage_valveState_tag    9
#define hydroponic_DataPackage_pumpState_tag     10
#define hydroponic_DataPackage_ledStatus_tag     11
#define hydroponic_HeartBeat_elapsedTime_tag     1
#define hydroponic_MessageOk_responseMessage_tag 1
#define hydroponic_MessageError_errorType_tag    1
#define hydroponic_MessageTimeout_timeoutMessage_tag 1
#define hydroponic_Hydroponic_messageType_tag    1
#define hydroponic_Hydroponic_dataPackage_tag    2
#define hydroponic_Hydroponic_heartBeat_tag      3
#define hydroponic_Hydroponic_messageOk_tag      4
#define hydroponic_Hydroponic_messageError_tag   5
#define hydroponic_Hydroponic_messageTimeout_tag 6

/* Struct field encoding specification for nanopb */
#define hydroponic_Hydroponic_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    messageType,       1) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (msg,dataPackage,msg.dataPackage),   2) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (msg,heartBeat,msg.heartBeat),   3) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (msg,messageOk,msg.messageOk),   4) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (msg,messageError,msg.messageError),   5) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (msg,messageTimeout,msg.messageTimeout),   6)
#define hydroponic_Hydroponic_CALLBACK NULL
#define hydroponic_Hydroponic_DEFAULT NULL
#define hydroponic_Hydroponic_msg_dataPackage_MSGTYPE hydroponic_DataPackage
#define hydroponic_Hydroponic_msg_heartBeat_MSGTYPE hydroponic_HeartBeat
#define hydroponic_Hydroponic_msg_messageOk_MSGTYPE hydroponic_MessageOk
#define hydroponic_Hydroponic_msg_messageError_MSGTYPE hydroponic_MessageError
#define hydroponic_Hydroponic_msg_messageTimeout_MSGTYPE hydroponic_MessageTimeout

#define hydroponic_DataPackage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   deviceID,          2) \
X(a, CALLBACK, SINGULAR, STRING,   sector,            3) \
X(a, STATIC,   SINGULAR, FLOAT,    eConductivity,     4) \
X(a, STATIC,   SINGULAR, FLOAT,    ph,                5) \
X(a, STATIC,   SINGULAR, FLOAT,    moisture,          6) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature,       7) \
X(a, STATIC,   SINGULAR, UINT32,   waterLevel,        8) \
X(a, STATIC,   SINGULAR, BOOL,     valveState,        9) \
X(a, STATIC,   SINGULAR, BOOL,     pumpState,        10) \
X(a, STATIC,   SINGULAR, BOOL,     ledStatus,        11)
#define hydroponic_DataPackage_CALLBACK pb_default_field_callback
#define hydroponic_DataPackage_DEFAULT NULL

#define hydroponic_HeartBeat_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   elapsedTime,       1)
#define hydroponic_HeartBeat_CALLBACK NULL
#define hydroponic_HeartBeat_DEFAULT NULL

#define hydroponic_MessageOk_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   responseMessage,   1)
#define hydroponic_MessageOk_CALLBACK pb_default_field_callback
#define hydroponic_MessageOk_DEFAULT NULL

#define hydroponic_MessageError_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   errorType,         1)
#define hydroponic_MessageError_CALLBACK pb_default_field_callback
#define hydroponic_MessageError_DEFAULT NULL

#define hydroponic_MessageTimeout_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   timeoutMessage,    1)
#define hydroponic_MessageTimeout_CALLBACK pb_default_field_callback
#define hydroponic_MessageTimeout_DEFAULT NULL

extern const pb_msgdesc_t hydroponic_Hydroponic_msg;
extern const pb_msgdesc_t hydroponic_DataPackage_msg;
extern const pb_msgdesc_t hydroponic_HeartBeat_msg;
extern const pb_msgdesc_t hydroponic_MessageOk_msg;
extern const pb_msgdesc_t hydroponic_MessageError_msg;
extern const pb_msgdesc_t hydroponic_MessageTimeout_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define hydroponic_Hydroponic_fields &hydroponic_Hydroponic_msg
#define hydroponic_DataPackage_fields &hydroponic_DataPackage_msg
#define hydroponic_HeartBeat_fields &hydroponic_HeartBeat_msg
#define hydroponic_MessageOk_fields &hydroponic_MessageOk_msg
#define hydroponic_MessageError_fields &hydroponic_MessageError_msg
#define hydroponic_MessageTimeout_fields &hydroponic_MessageTimeout_msg

/* Maximum encoded size of messages (where known) */
/* hydroponic_Hydroponic_size depends on runtime parameters */
/* hydroponic_DataPackage_size depends on runtime parameters */
/* hydroponic_MessageOk_size depends on runtime parameters */
/* hydroponic_MessageError_size depends on runtime parameters */
/* hydroponic_MessageTimeout_size depends on runtime parameters */
#define HYDROPONIC_HYDROPONIC_DATA_PB_H_MAX_SIZE hydroponic_HeartBeat_size
#define hydroponic_HeartBeat_size                6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
